import { beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { HandoverBriefButton } from './HandoverBriefButton';
import { ToastProvider } from './Toast';
import { api } from '@/lib/api';

/**
 * The brief is generated by someone going off watch and read by someone
 * coming on. The failure that matters is a section that is empty because a
 * call failed being read as "nothing to worry about".
 */

const empty = () => {
  for (const name of ['listIncidents', 'listPersonnel', 'listInventory', 'listStockAlerts',
                      'listShipments', 'listPurchaseOrders', 'listEvents'] as const) {
    vi.spyOn(api, name).mockResolvedValue([] as never);
  }
  vi.spyOn(api, 'getStationConditions').mockResolvedValue({ stations: { Maitri: 8 } });
};

const button = () => render(
  <ToastProvider><HandoverBriefButton station="Maitri" /></ToastProvider>,
);

const open = async () => {
  button();
  await userEvent.click(screen.getByRole('button', { name: /shift handover brief/i }));
  return screen.findByRole('dialog');
};

beforeEach(() => { vi.restoreAllMocks(); empty(); });

describe('generating the brief', () => {
  it('opens it to be read rather than dropping a file on disk', async () => {
    /** The handover usually happens over a desk. Reading is the common
     *  case; the file is the occasional one. */
    const dialog = await open();
    expect(dialog).toHaveTextContent('SHIFT HANDOVER BRIEF');
    expect(dialog).toHaveTextContent('Maitri Base');
  });

  it('offers download, copy and print once it is on screen', async () => {
    await open();
    for (const name of [/download/i, /copy/i, /print/i]) {
      expect(screen.getByRole('button', { name })).toBeInTheDocument();
    }
  });

  it('warns on screen when a section could not be read', async () => {
    /**
     * Said in the document and again as a toast. A roster section that is
     * blank because the call timed out, read at 3am, is indistinguishable
     * from a station where everybody is indoors.
     */
    vi.spyOn(api, 'listPersonnel').mockRejectedValue(new Error('unreachable'));
    const dialog = await open();
    await waitFor(() => expect(
      screen.getAllByText(/could not be read/i).length).toBeGreaterThanOrEqual(2));
    expect(dialog).toHaveTextContent('INCOMPLETE');
    expect(dialog).toHaveTextContent('Personnel roster');
    expect(dialog).toHaveTextContent('unknown, not as empty');
  });

  it('says nothing about missing sections when every source answered', async () => {
    await open();
    expect(screen.queryByText(/could not be read/i)).not.toBeInTheDocument();
  });

  it('reports a failure to generate at all instead of opening an empty dialog', async () => {
    vi.spyOn(api, 'getStationConditions').mockImplementation(() => {
      throw new Error('console is offline');
    });
    button();
    await userEvent.click(screen.getByRole('button', { name: /shift handover brief/i }));
    expect(await screen.findByText(/console is offline/i)).toBeInTheDocument();
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
  });
});

describe('the dialog', () => {
  it('closes on Escape', async () => {
    await open();
    await userEvent.keyboard('{Escape}');
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
  });

  it('closes on the close control', async () => {
    await open();
    await userEvent.click(screen.getByRole('button', { name: /close/i }));
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
  });

  it('copies the brief to the clipboard', async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    Object.assign(navigator, { clipboard: { writeText } });
    await open();
    await userEvent.click(screen.getByRole('button', { name: /copy/i }));
    await waitFor(() => expect(writeText).toHaveBeenCalled());
    expect(writeText.mock.calls[0][0]).toContain('SHIFT HANDOVER BRIEF');
  });

  it('says so rather than failing silently when the clipboard is unreachable', async () => {
    /** Clipboard access needs a secure context, which a station console on
     *  plain HTTP over the LAN is not. */
    Object.assign(navigator, {
      clipboard: { writeText: vi.fn().mockRejectedValue(new Error('insecure')) },
    });
    await open();
    await userEvent.click(screen.getByRole('button', { name: /copy/i }));
    expect(await screen.findByText(/select the text and copy it/i)).toBeInTheDocument();
  });
});
